# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\Python\Phigros.py\GUI\phi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhiPlayer(object):
    def setupUi(self, PhiPlayer):
        PhiPlayer.setObjectName("PhiPlayer")
        PhiPlayer.resize(971, 833)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        PhiPlayer.setFont(font)
        icon = QtGui.QIcon.fromTheme("Fusion")
        PhiPlayer.setWindowIcon(icon)
        PhiPlayer.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main = QtWidgets.QWidget(PhiPlayer)
        self.main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ratioKeeper = KeepRatioWidget(self.main)
        self.ratioKeeper.setAutoFillBackground(False)
        self.ratioKeeper.setStyleSheet("background: grey")
        self.ratioKeeper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ratioKeeper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ratioKeeper.setObjectName("ratioKeeper")
        self.player = IntegratedPlayer(self.ratioKeeper)
        self.player.setGeometry(QtCore.QRect(0, 150, 951, 401))
        self.player.setStyleSheet("background:black")
        self.player.setObjectName("player")
        self.verticalLayout.addWidget(self.ratioKeeper)
        self.seekBarArea = QtWidgets.QWidget(self.main)
        self.seekBarArea.setMinimumSize(QtCore.QSize(0, 24))
        self.seekBarArea.setMaximumSize(QtCore.QSize(16777215, 24))
        self.seekBarArea.setObjectName("seekBarArea")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.seekBarArea)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startTime = TimeLableWidget(self.seekBarArea)
        self.startTime.setMinimumSize(QtCore.QSize(50, 0))
        self.startTime.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.startTime.setFont(font)
        self.startTime.setText("00:00")
        self.startTime.setAlignment(QtCore.Qt.AlignCenter)
        self.startTime.setObjectName("startTime")
        self.horizontalLayout_2.addWidget(self.startTime)
        self.seekBar = QtWidgets.QSlider(self.seekBarArea)
        self.seekBar.setMinimum(0)
        self.seekBar.setMaximum(150)
        self.seekBar.setOrientation(QtCore.Qt.Horizontal)
        self.seekBar.setObjectName("seekBar")
        self.horizontalLayout_2.addWidget(self.seekBar)
        self.endTime = TimeLableWidget(self.seekBarArea)
        self.endTime.setMinimumSize(QtCore.QSize(50, 0))
        self.endTime.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.endTime.setFont(font)
        self.endTime.setText("xx:xx")
        self.endTime.setAlignment(QtCore.Qt.AlignCenter)
        self.endTime.setObjectName("endTime")
        self.horizontalLayout_2.addWidget(self.endTime)
        self.verticalLayout.addWidget(self.seekBarArea)
        self.controlAreaOut = QtWidgets.QWidget(self.main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlAreaOut.sizePolicy().hasHeightForWidth())
        self.controlAreaOut.setSizePolicy(sizePolicy)
        self.controlAreaOut.setMaximumSize(QtCore.QSize(16777215, 60))
        self.controlAreaOut.setObjectName("controlAreaOut")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.controlAreaOut)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.controlArea = QtWidgets.QWidget(self.controlAreaOut)
        self.controlArea.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setKerning(True)
        self.controlArea.setFont(font)
        self.controlArea.setObjectName("controlArea")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.controlArea)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.capture = QtWidgets.QPushButton(self.controlArea)
        self.capture.setMinimumSize(QtCore.QSize(40, 35))
        self.capture.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("Material Icons")
        font.setPointSize(18)
        font.setKerning(True)
        self.capture.setFont(font)
        self.capture.setText("")
        self.capture.setFlat(True)
        self.capture.setObjectName("capture")
        self.horizontalLayout_3.addWidget(self.capture)
        self.start = startButton(self.controlArea)
        self.start.setMinimumSize(QtCore.QSize(40, 35))
        self.start.setMaximumSize(QtCore.QSize(40, 35))
        font = QtGui.QFont()
        font.setFamily("Material Icons")
        font.setPointSize(25)
        font.setKerning(False)
        self.start.setFont(font)
        self.start.setText("")
        self.start.setDefault(False)
        self.start.setFlat(True)
        self.start.setObjectName("start")
        self.horizontalLayout_3.addWidget(self.start)
        self.start.raise_()
        self.capture.raise_()
        self.horizontalLayout.addWidget(self.controlArea, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.controlAreaOut)
        PhiPlayer.setCentralWidget(self.main)
        self.menubar = QtWidgets.QMenuBar(PhiPlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        PhiPlayer.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(PhiPlayer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlayPause = QtWidgets.QAction(PhiPlayer)
        self.actionPlayPause.setVisible(True)
        self.actionPlayPause.setIconVisibleInMenu(True)
        self.actionPlayPause.setShortcutVisibleInContextMenu(True)
        self.actionPlayPause.setObjectName("actionPlayPause")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionPlayPause)
        self.menubar.addAction(self.menu.menuAction())
        self.startTime.setBuddy(self.seekBar)
        self.endTime.setBuddy(self.seekBar)

        self.retranslateUi(PhiPlayer)
        self.seekBar.sliderPressed.connect(self.player.pause) # type: ignore
        self.seekBar.sliderReleased.connect(self.player.start) # type: ignore
        self.player.timeUpdate['int'].connect(self.seekBar.setValue) # type: ignore
        self.player.endTimeLoaded['int'].connect(self.endTime.setTime) # type: ignore
        self.player.timeUpdate['int'].connect(self.startTime.setTime) # type: ignore
        self.player.rangeLoaded['int','int'].connect(self.seekBar.setRange) # type: ignore
        self.seekBar.sliderMoved['int'].connect(self.player.seek) # type: ignore
        self.seekBar.valueChanged['int'].connect(self.startTime.setTime) # type: ignore
        self.start.pressed.connect(self.player.toggle) # type: ignore
        self.capture.pressed.connect(self.player.capture) # type: ignore
        self.actionPlayPause.triggered.connect(self.player.toggle) # type: ignore
        self.actionOpen.triggered.connect(PhiPlayer.openFileToRead) # type: ignore
        self.player.toogled.connect(self.start.toggleText) # type: ignore
        self.player.bePaused.connect(self.start.setPlay) # type: ignore
        self.player.bePlayed.connect(self.start.setPause) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PhiPlayer)
        PhiPlayer.setTabOrder(self.capture, self.start)

    def retranslateUi(self, PhiPlayer):
        _translate = QtCore.QCoreApplication.translate
        PhiPlayer.setWindowTitle(_translate("PhiPlayer", "Phigros player"))
        self.player.setWhatsThis(_translate("PhiPlayer", "The main player"))
        self.capture.setToolTip(_translate("PhiPlayer", "停止"))
        self.start.setToolTip(_translate("PhiPlayer", "播放"))
        self.menu.setTitle(_translate("PhiPlayer", "文件(&F)"))
        self.actionOpen.setText(_translate("PhiPlayer", "打开(&O)"))
        self.actionOpen.setShortcut(_translate("PhiPlayer", "Ctrl+O"))
        self.actionPlayPause.setText(_translate("PhiPlayer", "开始/暂停"))
        self.actionPlayPause.setShortcut(_translate("PhiPlayer", "Space"))
from integrated import IntegratedPlayer
from keepRatioWidget import KeepRatioWidget
from startButton import startButton
from timeLable import TimeLableWidget
