# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\Python\Phigros.py\GUI\phi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_win(object):
    def setupUi(self, win):
        win.setObjectName("win")
        win.resize(971, 833)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        win.setFont(font)
        icon = QtGui.QIcon.fromTheme("Fusion")
        win.setWindowIcon(icon)
        win.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main = QtWidgets.QWidget(win)
        self.main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.player = PhiPlayer(self.main)
        self.player.setObjectName("player")
        self.verticalLayout.addWidget(self.player)
        win.setCentralWidget(self.main)
        self.menubar = QtWidgets.QMenuBar(win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        win.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(win)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlayPause = QtWidgets.QAction(win)
        self.actionPlayPause.setVisible(True)
        self.actionPlayPause.setIconVisibleInMenu(True)
        self.actionPlayPause.setShortcutVisibleInContextMenu(True)
        self.actionPlayPause.setObjectName("actionPlayPause")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionPlayPause)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(win)
        self.actionOpen.triggered.connect(self.player.openFileToRead)
        self.actionPlayPause.triggered.connect(self.player.toogle)
        QtCore.QMetaObject.connectSlotsByName(win)

    def retranslateUi(self, win):
        _translate = QtCore.QCoreApplication.translate
        win.setWindowTitle(_translate("win", "Phigros player"))
        self.menu.setTitle(_translate("win", "文件(&F)"))
        self.actionOpen.setText(_translate("win", "打开(&O)"))
        self.actionOpen.setShortcut(_translate("win", "Ctrl+O"))
        self.actionPlayPause.setText(_translate("win", "开始/暂停"))
        self.actionPlayPause.setShortcut(_translate("win", "Space"))
from .Player import PhiPlayer
