# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\Python\Phigros.py\GUI\phi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhiPlayer(object):
    def setupUi(self, PhiPlayer):
        PhiPlayer.setObjectName("PhiPlayer")
        PhiPlayer.resize(971, 833)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        PhiPlayer.setFont(font)
        icon = QtGui.QIcon.fromTheme("Fusion")
        PhiPlayer.setWindowIcon(icon)
        PhiPlayer.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.main = QtWidgets.QWidget(PhiPlayer)
        self.main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setObjectName("main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        PhiPlayer.setCentralWidget(self.main)
        self.menubar = QtWidgets.QMenuBar(PhiPlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 971, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        PhiPlayer.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(PhiPlayer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlayPause = QtWidgets.QAction(PhiPlayer)
        self.actionPlayPause.setVisible(True)
        self.actionPlayPause.setIconVisibleInMenu(True)
        self.actionPlayPause.setShortcutVisibleInContextMenu(True)
        self.actionPlayPause.setObjectName("actionPlayPause")
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionPlayPause)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(PhiPlayer)
        self.actionOpen.triggered.connect(PhiPlayer.openFileToRead)
        QtCore.QMetaObject.connectSlotsByName(PhiPlayer)

    def retranslateUi(self, PhiPlayer):
        _translate = QtCore.QCoreApplication.translate
        PhiPlayer.setWindowTitle(_translate("PhiPlayer", "Phigros player"))
        self.menu.setTitle(_translate("PhiPlayer", "文件(&F)"))
        self.actionOpen.setText(_translate("PhiPlayer", "打开(&O)"))
        self.actionOpen.setShortcut(_translate("PhiPlayer", "Ctrl+O"))
        self.actionPlayPause.setText(_translate("PhiPlayer", "开始/暂停"))
        self.actionPlayPause.setShortcut(_translate("PhiPlayer", "Space"))
